### ISSUE TITLE
What is the decoder of the model?

### ISSUE THREAD

**Issue by gavinwxy** [JoyHuYY1412/S4Former#2]
Hi, could you please share more info on the model implementation, like the decoder design for your work? Thanks.

**Comment by JoyHuYY1412** [comment]
> Hi, could you please share more info on the model implementation, like the decoder design for your work? Thanks.

Hi, thank you for your interest, currently our project is undergoing patent submission. I will release the code once it is done. 
The decoder for SETR is setr_up_head in mmsegmentation implementation.

**Comment by gavinwxy** [comment]
Thank you for your reply.
