### ISSUE TITLE
The weight of different losses

### ISSUE THREAD

**Issue by zdk258** [JoyHuYY1412/S4Former#3]
作者你好，请问最终损失之间的权重是下面这样吗？
`L = L_sup + 0.5 * (L_unsup_CE_A + L_unsup_CE_PASA + L_unsup_NCR_A + L_unsup_NCR_PASA)`
还是这样：
`L = L_sup + 0.5 * (L_unsup_CE_A + L_unsup_CE_PASA) + (L_unsup_NCR_A + L_unsup_NCR_PASA)`
损失之间的权重对结果影响大吗？

**Comment by JoyHuYY1412** [comment]
您好，损失之间的权重对结果影响不大 (我也没测太多这个超参)，我这里使用的是`L = L_sup + 0.5 *  (L_unsup_CE_PASA + L_unsup_NCR)`. 您也可以留下邮箱 （公司的开源似乎还是卡住了）

**Comment by zdk258** [comment]
谢谢解答
